# .cicleci/config.yml

defaults: &defaults
  docker:
    - image: circleci/openjdk:11

jobs:
  setup:
   <<: *defaults
   steps:
     - checkout
     - run:
        name: set up Environment
        command: |
          # build command
          echo "this is shared setup"

  build:
   <<: *defaults
   steps:
     - setup: 
     - run:
         name: Build Java App
         command: |
         #build command
         ./gradlew build

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global-context
