# .cicleci/config.yml

defaults: &defaults
  docker:
    - image: circleci/openjdk:11

jobs:
  build:
   <<: *defaults
   steps:
     - checkout
     - run:
        name: Build Java App
        command: |
          # build command
          ./gradlew build

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global-context